services:
  api:
    build:
      context: ..
      dockerfile: backend/packages/api/devops/Dockerfile
    container_name: api
    restart: always
    ports:
      - "8000:8000"  # Adjust according to your microservice's exposed port
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  micronetwork:
    name: micronetwork
    external: true
